 version: '3.4'

 services:
   marist-app:
     image: hastingsn25/marist-app
     build: .
     environment:
       NODE_ENV: production
       TZ: America\Chicago
       REDIS_HOST: docker-main.local
       REDIS_PORT: 6379
     ports:
       - 80:3001