name: Docker Build

on:
  workflow_dispatch:

env:
  IMAGE_NAME: marist-app
  USER: hastingsn25
  

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.USER }}/${{ env.IMAGE_NAME }}
          flavor: latest=true
        
      - name: Log into registry Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.user }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Latest Docker Image
        id: build-and-push-latest
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.USER }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
